@AzureDigitalTwinsQueryApi_HostAddress = http://localhost:5075

GET {{AzureDigitalTwinsQueryApi_HostAddress}}/api
Content-Type: application/json

###

POST {{AzureDigitalTwinsQueryApi_HostAddress}}/api/q
Content-Type: application/json

{
  "Query": "SELECT * FROM digitaltwins"
}

###
